editor:
  add_fields:
    TAXONOMY:
    - otherCatalogNumber
  hide_fields:
  - order
  - family
  - scientificName
  - speciesNameAuthorship
  - otherCatalogNumber
locations:
  # "local"
  # Edited files will live somewhere like this: S:/VoucherVision/Transcription/UNIQNAME/WORKBENCH_NAME/Transcription/transcribed__edited__2024_10_08T16_40_31.xlsx
  project_dir: "S:/VoucherVision/Transcription"