[theme]
    primaryColor = "#16a616"
    backgroundColor="#1a1a1a"
    secondaryBackgroundColor="#303030"
    textColor = "cccccc"

[server]
    enableStaticServing = true
    runOnSave = true
    port = 8523
    maxUploadSize = 51200

[runner]
    fastReruns = false